[package]
name = "sigmoid-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
fluentbase-sdk = { git = "https://github.com/fluentlabs-xyz/fluentbase", tag = "v0.3.6-dev", default-features = false }
alloy-sol-types = { version = "0.7", default-features = false }

[dev-dependencies]
# For testing, we'll use the same SDK without special features
fluentbase-sdk = { git = "https://github.com/fluentlabs-xyz/fluentbase", tag = "v0.3.6-dev" }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[features]
default = []

# Required for no_std
[profile.dev]
panic = "abort"

[profile.test]
panic = "unwind"